export const CharacterInitialValues = {
    //CHARACTER INFO
    _id: '',
    characterType: '',
    characterName: '',
    characterClass: '',
    characterRace: '',
    characterBackground: '',
    characterBackstory: '',
    characterAllies: '',
    characterIdeals: '',
    characterPersonalityTraits: '',
    characterBonds: '',
    characterFlaws: '',
    characterTreasure: '',
    characterPhoto: '',
    playerName: '',
    exp: 0,
    hasInspiration: false,
    isAlive: false,
    teamId: '',

    //SKILLS
    characterStrength: 0,
    characterDexterity: 0,
    characterConstitution: 0,
    characterIntelligence: 0,
    characterWisdom: 0,
    characterCharisma: 0,
    characterProficiencyBonus: 0,
    characterPassiveWisdom: 0,
    characterSpeed: 0,
    characterHP: 0,
    characterInitiative: 0,
    damageResistances: '',
    damageImmunities: '',
    conditionImmunities: '',
    senses: '',

    //SAVING THROWS
    hasStrengthSavingThrowProficiency: false,
    hasDexteritySavingThrowProficiency: false,
    hasConstitutionSavingThrowProficiency: false,
    hasIntelligenceSavingThrowProficiency: false,
    hasWisdomSavingThrowProficiency: false,
    hasCharismaSavingThrowProficiency: false,

    //SKILLS
    hasAcrobatics: false,
    hasAnimalHandling: false,
    hasArcana: false,
    hasAthletics: false,
    hasDeception: false,
    hasHistory: false,
    hasInsight: false,
    hasIntimidation: false,
    hasInvestigation: false,
    hasMedicine: false,
    hasNature: false,
    hasPerception: false,
    hasPerformance: false,
    hasPersuasion: false,
    hasReligion: false,
    hasSleightOfHands: false,
    hasStealth: false,
    hasSurvival: false,

    //EQUIPMENT
    armorClass: 0,

    //TALENTS
    featuresAndTraits: '',
    otherProficienciesAndLanguages: '',
}