export const ConditionTypes = {
    blinded: "Blinded",
    charmed: "Charmed",
    deafened: "Deafened",
    exhaustion: "Exhaustion",
    frightened: "Frightened",
    grappled: "Grappled",
    incapacitated: "Incapacitated",
    invisible: "Invisible",
    paralyzed: "Paralyzed",
    petrified: "Petrified",
    poisoned: "Poisoned",
    prone: "Prone",
    restrained: "Restrained",
    stunned: "Stunned",
    unconscious: "Unconscious",
}